language: node_js
node_js:
  - lts/*
addons:
  chrome: stable
  ssh_known_hosts: 35.233.171.1
services: mongodb
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
  - npm run build-app
  - npm test
  - npm run e2e
  - if [ "$BRANCH" == "master" ]; then
      openssl aes-256-cbc -K $encrypted_a86a9c8d2738_key -iv $encrypted_a86a9c8d2738_iv -in deploy-rsa.enc -out /tmp/deploy-rsa -d;
      chmod 600 /tmp/deploy-rsa;
      eval `ssh-agent`;
      ssh-add /tmp/deploy-rsa;
      ssh kailangfu@35.233.171.1 "cd repositories/touhou-card-game-nodejs/ && git pull && npm ci && npm run build-app && pm2 restart tcg-server";
      kill $SSH_AGENT_PID;
      rm -f /tmp/deploy-rsa;
    fi
after_success: npm run coverage
